server:
  port: 18086

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.88.128:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.88.128
    virtual-host: /admin
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 4
feign:
  sentinel:
    enabled: true
