server:
  port: 18089

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    discovery-client-enabled: true
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false

feign:
  sentinel:
    enabled: true


logging:
  level:
    com.atguigu.gmall: debug



jwt:
  pubKeyPath: E:\004_Java_Study\001_MyWork\006_OnlineMall\01_project\rsa\rsa.pub
  priKeyPath: E:\004_Java_Study\001_MyWork\006_OnlineMall\01_project\rsa\rsa.pri
  secret: 234
  expire: 180
  cookieName: GMALL-TOKEN
  nickName: unick

