server:
  port: 18083

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    discovery-client-enabled: false
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_wms
    username: root
    password: 123456
  redis:
    host: 192.168.88.128
  rabbitmq:
    host: 192.168.88.128
    virtual-host: /admin
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 4
    publisher-confirm-type: CORRELATED
    publisher-returns: true
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu.gmall: debug
